version: 2
jobs:
  build:
    machine: 
      enabled: true
      image: circleci/classic:latest
    steps:
      checkout
      run:
        name: init lineage repo
        command: repo init -u git://github.com/germknoedel/android.git -b cm-14.1
      run:
        name: init lineage repo
        command: uname -a
